yandex-lavka:
  earning:
    FOOT: 2
    BIKE: 3
    AUTO: 4
  rating:
    FOOT: 3
    BIKE: 2
    AUTO: 1
  max-weight:
    FOOT: 10
    BIKE: 20
    AUTO: 40
  max-order-amount:
    FOOT: 2
    BIKE: 4
    AUTO: 7
  regions-on-delivery:
    FOOT: 1
    BIKE: 2
    AUTO: 3
  time-on-first-order:
    FOOT: 25
    BIKE: 12
    AUTO: 8
  time-on-next-order:
    FOOT: 10
    BIKE: 8
    AUTO: 4
  cost-coef-next-order: 0.8

spring:
  datasource:
#    username: ${POSTGRES_USER}
#    password: ${POSTGRES_PASSWORD}
#    url: jdbc:postgresql://${POSTGRES_SERVER}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: postgres
    password: postgres
    url: jdbc:postgresql://db:5432/postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format_sql: false
        show_sql: false
      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED
    open-in-view: false

    hibernate:
      ddl-auto: update

resilience4j:
  ratelimiter:
    configs:
      default:
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 100ms

springdoc:
  api-docs:
    enabled: true
    path: /openapi/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui